disabled = false
languageCode = "fr"
languageName = "Francais"
weight = 1
title = "Société de Tir<br>le Vésinet Chatou"

[params]
  displayName = "FR"
  isoCode = "fr"
  rtl = false
  dateFormat = "2 Janvier 2006"
  logo = "logo.png"
  # secondaryLogo = "img/secondary-logo.png"
  # description = "My awesome website"
  # copyright = "Copy, _right?_ :thinking_face:"

 [params.author]
   name = "Daniel Sebton"
   email = "dsebton@gmail.com"
#   headline = "I'm only human"
#   bio = "A little bit about you"
