disabled = false
languageCode = "fr"
languageName = "Francais"
weight = 1
title = "Société de Tir<br>le Vésinet Chatou"

[params]
  displayName = "FR"
  isoCode = "fr"
  rtl = false
  dateFormat = "2 January 2006"
  logo = "logo.png"
  # secondaryLogo = "img/secondary-logo.png"
  # description = "My awesome website"
  # copyright = "Copy, _right?_ :thinking_face:"

 [params.author]
   name = "Société de Tir le Vésinet Chatou"
   email = "contact@stvc.fr"
   image = "logo_square.png"
   headline = "Association à but non lucratif fondée en 1907"
   bio = "La STVC est une association loi 1901 à but non lucratif qui gère le stand et y accueille ses adhérents pour la pratique du tir sportif, ainsi que des policiers municipaux pour leurs formations ou entraînements lorsque leur commune a signé une convention avec l'association."
