# -- Main Menu --
# The main menu is displayed in the header at the top of the page.
# Acceptable parameters are name, pageRef, page, url, title, weight.
# 
# The simplest menu configuration is to provide:
#   name = The name to be displayed for this menu link
#   pageRef = The identifier of the page or section to link to
#
# By default the menu is ordered alphabetically. This can be
# overridden by providing a weight value. The menu will then be
# ordered by weight from lowest to highest.

[[main]]
  name = "Accueil"
  pageRef = "accueil"
  weight = 1

[[main]]
  name = "L'association"
  weight = 2

[[main]]
  name = "Historique"
  parent = "L'association"
  pageRef = "historique"
  weight = 1

[[main]]
  name = "Les Stands"
  parent = "L'association"
  pageRef = "stands"
  weight = 2

[[main]]
  name = "Infos Pratiques"
  pageRef = "posts"
  weight = 3

[[main]]
  name = "Horaires"
  parent = "Infos Pratiques"
  pageRef = "horaires"
  weight = 1

[[main]]
  name = "Tarifs"
  parent = "Infos Pratiques"
  pageRef = "tarifs"
  weight = 2

[[main]]
  name = "Liens Utiles"
  parent = "Infos Pratiques"
  pageRef = ""
  weight = 3

[[main]]
  name = "QCM et avis préalable"
  parent = "Infos Pratiques"
  pageRef = ""
  weight = 4


[[main]]
  name = "Inscription"
  pageRef = ""
  weight = 4

[[main]]
  name = "Adhésion"
  parent = "Inscription"
  pageRef = "adhesion"
  weight = 1

[[main]]
  name = "Réinscription"
  parent = "Inscription"
  pageRef = "réinscription"
  weight = 2


[[main]]
  name = "Règlement intérieur"
  pageRef = "règlement"
  weight = 5

#[[main]]
#  name = "Tags"
#  pageRef = "tags"
#  weight = 30


# -- Footer Menu --
# The footer menu is displayed at the bottom of the page, just before
# the copyright notice. Configure as per the main menu above.


# [[footer]]
#   name = "Tags"
#   pageRef = "tags"
#   weight = 10

# [[footer]]
#   name = "Categories"
#   pageRef = "categories"
#   weight = 20
