---
version: "3.9"
services:
  webserver:
    image: lipanski/docker-static-website:latest
    restart: always
    ports:
      - "45458:3000"
    volumes:
      - ./public:/home/static
      - ./httpd.conf:/home/static/httpd.conf:ro
